-- FaceGuard cloud schema: ESP32-CAM live metadata, fall events and private media.
-- Live 25 FPS frames are relayed by the inference server and are intentionally
-- not persisted. Only event evidence and the latest device state are stored.

create extension if not exists pgcrypto;

create table if not exists public.devices (
  id text primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null default 'Kamera FaceGuard',
  location text not null default 'Belum ditetapkan',
  server_url text,
  detection_enabled boolean not null default true,
  target_fps smallint not null default 25 check (target_fps between 1 and 25),
  inference_fps smallint not null default 5 check (inference_fps between 1 and 10),
  fall_confirm_seconds numeric(4,2) not null default 1.50 check (fall_confirm_seconds between 0.5 and 10),
  online boolean not null default false,
  stream_fps numeric(5,2) not null default 0,
  last_seen timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint devices_id_format check (id ~ '^[A-Za-z0-9_-]{3,64}$')
);

create table if not exists public.aktiviti_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text references public.devices(id) on delete cascade,
  status text not null default 'pergerakan_dikesan',
  confidence numeric(5,4),
  image_path text,
  video_path text,
  image_url text,
  video_url text,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.aktiviti_log add column if not exists device_id text;
alter table public.aktiviti_log add column if not exists status text;
alter table public.aktiviti_log add column if not exists confidence numeric(5,4);
alter table public.aktiviti_log add column if not exists image_path text;
alter table public.aktiviti_log add column if not exists video_path text;
alter table public.aktiviti_log add column if not exists image_url text;
alter table public.aktiviti_log add column if not exists video_url text;
alter table public.aktiviti_log add column if not exists metadata jsonb default '{}'::jsonb;

create index if not exists aktiviti_log_device_created_idx
  on public.aktiviti_log (device_id, created_at desc);
create index if not exists devices_owner_idx on public.devices (owner_id);

create or replace function public.set_faceguard_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists devices_set_updated_at on public.devices;
create trigger devices_set_updated_at
before update on public.devices
for each row execute function public.set_faceguard_updated_at();

alter table public.devices enable row level security;
alter table public.aktiviti_log enable row level security;

drop policy if exists "owner reads own devices" on public.devices;
create policy "owner reads own devices"
on public.devices for select to authenticated
using ((select auth.uid()) = owner_id);

drop policy if exists "owner creates own devices" on public.devices;
create policy "owner creates own devices"
on public.devices for insert to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists "owner updates own devices" on public.devices;
create policy "owner updates own devices"
on public.devices for update to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "owner deletes own devices" on public.devices;
create policy "owner deletes own devices"
on public.devices for delete to authenticated
using ((select auth.uid()) = owner_id);

drop policy if exists "owner reads own activity" on public.aktiviti_log;
create policy "owner reads own activity"
on public.aktiviti_log for select to authenticated
using (
  exists (
    select 1 from public.devices d
    where d.id = aktiviti_log.device_id
      and d.owner_id = (select auth.uid())
  )
);

grant select, insert, update, delete on public.devices to authenticated;
grant select on public.aktiviti_log to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'faceguard-storage',
  'faceguard-storage',
  false,
  52428800,
  array['image/jpeg', 'video/mp4', 'video/x-msvideo']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "owner reads own faceguard media" on storage.objects;
create policy "owner reads own faceguard media"
on storage.objects for select to authenticated
using (
  bucket_id = 'faceguard-storage'
  and exists (
    select 1 from public.devices d
    where d.id = (storage.foldername(name))[1]
      and d.owner_id = (select auth.uid())
  )
);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'aktiviti_log'
  ) then
    alter publication supabase_realtime add table public.aktiviti_log;
  end if;
end;
$$;

comment on table public.devices is 'Owner-controlled ESP32-CAM configuration and latest status.';
comment on table public.aktiviti_log is 'Server-created fall events; media paths point to the private FaceGuard bucket.';

-- Existing project helper was SECURITY DEFINER and inherited executable grants.
-- It is a dashboard helper, not part of the client API.
do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    revoke execute on function public.rls_auto_enable() from public;
    revoke execute on function public.rls_auto_enable() from anon;
    revoke execute on function public.rls_auto_enable() from authenticated;
  end if;
end;
$$;
