create extension if not exists pgcrypto;

create table if not exists public.faceguard_devices (
  id uuid primary key default gen_random_uuid(),
  device_code text not null unique,
  device_secret_hash text not null,
  name text not null default 'Kamera FaceGuard',
  owner_id uuid not null references auth.users(id) on delete cascade,
  local_ip text,
  firmware_version text,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.faceguard_device_members (
  device_id uuid not null references public.faceguard_devices(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('owner', 'editor', 'viewer')),
  added_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (device_id, user_id)
);

create table if not exists public.faceguard_setup_sessions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  setup_token_hash text not null unique,
  claimed_device_id uuid references public.faceguard_devices(id) on delete set null,
  expires_at timestamptz not null default (now() + interval '10 minutes'),
  created_at timestamptz not null default now()
);

create table if not exists public.faceguard_invites (
  id uuid primary key default gen_random_uuid(),
  device_id uuid not null references public.faceguard_devices(id) on delete cascade,
  invite_token_hash text not null unique,
  role text not null default 'viewer' check (role in ('editor', 'viewer')),
  created_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null default (now() + interval '24 hours'),
  accepted_by uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.faceguard_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null unique,
  platform text not null check (platform in ('android', 'ios', 'web')),
  device_instance_id text,
  updated_at timestamptz not null default now()
);

alter table public.aktiviti_log
  add column if not exists device_id uuid references public.faceguard_devices(id) on delete cascade,
  add column if not exists storage_path text,
  add column if not exists clip_paths jsonb not null default '[]'::jsonb,
  add column if not exists event_kind text not null default 'motion';

create index if not exists faceguard_device_members_user_idx
  on public.faceguard_device_members(user_id, device_id);
create index if not exists faceguard_devices_owner_idx
  on public.faceguard_devices(owner_id);
create index if not exists faceguard_setup_sessions_owner_idx
  on public.faceguard_setup_sessions(owner_id, expires_at desc);
create index if not exists faceguard_activity_device_created_idx
  on public.aktiviti_log(device_id, created_at desc);
create index if not exists faceguard_push_tokens_user_idx
  on public.faceguard_push_tokens(user_id);

create or replace function public.faceguard_limit_device_members()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if (select count(*) from public.faceguard_device_members
      where device_id = new.device_id) >= 5 then
    raise exception 'FaceGuard membenarkan maksimum 5 pengguna bagi satu kamera';
  end if;
  return new;
end;
$$;

drop trigger if exists faceguard_limit_device_members_trigger
  on public.faceguard_device_members;
create trigger faceguard_limit_device_members_trigger
before insert on public.faceguard_device_members
for each row execute function public.faceguard_limit_device_members();

alter table public.faceguard_devices enable row level security;
alter table public.faceguard_device_members enable row level security;
alter table public.faceguard_setup_sessions enable row level security;
alter table public.faceguard_invites enable row level security;
alter table public.faceguard_push_tokens enable row level security;

revoke all on public.faceguard_devices from anon;
revoke all on public.faceguard_device_members from anon;
revoke all on public.faceguard_setup_sessions from anon;
revoke all on public.faceguard_invites from anon;
revoke all on public.faceguard_push_tokens from anon;

grant select on public.faceguard_devices to authenticated;
grant select on public.faceguard_device_members to authenticated;
grant select on public.faceguard_setup_sessions to authenticated;
grant select on public.faceguard_invites to authenticated;
grant select, insert, update, delete on public.faceguard_push_tokens to authenticated;
grant select, delete on public.aktiviti_log to authenticated;
grant usage, select on sequence public.faceguard_push_tokens_id_seq to authenticated;

drop policy if exists "FaceGuard members read devices" on public.faceguard_devices;
create policy "FaceGuard members read devices"
on public.faceguard_devices for select to authenticated
using (
  owner_id = (select auth.uid())
  or exists (
    select 1 from public.faceguard_device_members member
    where member.device_id = id
      and member.user_id = (select auth.uid())
  )
);

drop policy if exists "FaceGuard members read memberships" on public.faceguard_device_members;
create policy "FaceGuard members read memberships"
on public.faceguard_device_members for select to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1 from public.faceguard_devices device
    where device.id = device_id
      and device.owner_id = (select auth.uid())
  )
);

drop policy if exists "FaceGuard owners read setup sessions" on public.faceguard_setup_sessions;
create policy "FaceGuard owners read setup sessions"
on public.faceguard_setup_sessions for select to authenticated
using (owner_id = (select auth.uid()));

drop policy if exists "FaceGuard owners read invites" on public.faceguard_invites;
create policy "FaceGuard owners read invites"
on public.faceguard_invites for select to authenticated
using (
  created_by = (select auth.uid())
  or exists (
    select 1 from public.faceguard_device_members member
    where member.device_id = faceguard_invites.device_id
      and member.user_id = (select auth.uid())
  )
);

drop policy if exists "FaceGuard users manage own push tokens" on public.faceguard_push_tokens;
create policy "FaceGuard users manage own push tokens"
on public.faceguard_push_tokens for all to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists "FaceGuard members read activity" on public.aktiviti_log;
create policy "FaceGuard members read activity"
on public.aktiviti_log for select to authenticated
using (
  exists (
    select 1 from public.faceguard_device_members member
    where member.device_id = aktiviti_log.device_id
      and member.user_id = (select auth.uid())
  )
);

drop policy if exists "FaceGuard editors delete activity" on public.aktiviti_log;
create policy "FaceGuard editors delete activity"
on public.aktiviti_log for delete to authenticated
using (
  exists (
    select 1 from public.faceguard_device_members member
    where member.device_id = aktiviti_log.device_id
      and member.user_id = (select auth.uid())
      and member.role in ('owner', 'editor')
  )
);

drop policy if exists "FaceGuard members read private media" on storage.objects;
create policy "FaceGuard members read private media"
on storage.objects for select to authenticated
using (
  bucket_id = 'faceguard-storage'
  and exists (
    select 1 from public.faceguard_device_members member
    where member.user_id = (select auth.uid())
      and member.device_id = case
        when (storage.foldername(name))[1] ~
          '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        then ((storage.foldername(name))[1])::uuid
        else null
      end
  )
);

drop policy if exists "FaceGuard editors delete private media" on storage.objects;
create policy "FaceGuard editors delete private media"
on storage.objects for delete to authenticated
using (
  bucket_id = 'faceguard-storage'
  and exists (
    select 1 from public.faceguard_device_members member
    where member.user_id = (select auth.uid())
      and member.role in ('owner', 'editor')
      and member.device_id = case
        when (storage.foldername(name))[1] ~
          '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        then ((storage.foldername(name))[1])::uuid
        else null
      end
  )
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'faceguard_devices'
  ) then
    alter publication supabase_realtime add table public.faceguard_devices;
  end if;
end;
$$;
